# Generated by Django 3.2.8 on 2021-11-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_details_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='role',
            field=models.CharField(choices=[('regular', 'regular'), ('admin', 'admin')], default='regular', max_length=50),
        ),
    ]
