# Generated by Django 3.2.8 on 2021-10-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happygut', '0005_alter_article_list_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_list',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
