# Generated by Django 3.2.8 on 2021-10-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happygut', '0006_alter_article_list_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_list',
            name='full',
            field=models.CharField(max_length=10000),
        ),
    ]
