# Generated by Django 3.2.8 on 2021-10-31 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happygut', '0010_auto_20211031_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_list',
            name='image',
            field=models.CharField(max_length=10000),
        ),
    ]
