# Generated by Django 3.2.8 on 2021-11-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happygut', '0012_auto_20211104_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Save_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_heading', models.CharField(max_length=1000)),
            ],
        ),
    ]
